import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import Header from "./search-bar";
import { Menu, } from "./menu";
import { queryStockInfo } from "@/api";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};





export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const stocks = await queryStockInfo()
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header stocks={stocks} />
        <div className="flex items-start">
          <Menu className="w-40 flex-shrink-0 min-h-[calc(100vh-4rem)] border-r-2 border-gray-300 " />
          <div className="p-4 flex-1 max-w-[calc(100vw-10rem)]">
            <Suspense fallback={<h1>Loading...</h1>}>
              {children}
            </Suspense>
          </div>
        </div>
      </body>
    </html>
  );
}
